### ISSUE TITLE
what's your future plans?

### ISSUE THREAD

**Issue by Lillecarl** [codekuu/evdev-trigger#2]
https://github.com/Lillecarl/nixos/blob/master/scripts/remapper.py
https://github.com/philipl/evdevremapkeys/pull/46
https://github.com/gvalkov/python-evdev/pull/216

Just found your repo in my Github flow, what's your plans? I've been meaning to make something reusable out of my remapper script.

// Carlis 😸

**Comment by codekuu** [comment]
Halloj Carlis!

I don't have any specific plans except maybe to add more functionality. I’m not using this for any specific projects at the moment, but I'll maintain it if people find it useful.

I think the next step is to add auto-installation (package management) for the Actions.

Currently, if you use an action that requires another module not installed in evdev-trigger, it will fail. You would need to manually install it using pip. However, I plan to add a feature that automatically installs the necessary dependencies within evdev

**Comment by Lillecarl** [comment]
@codekuu I'd like some help with the python-evdev PR. It adds type stubs for all keycodes and shit, but it's really hacky atm.

My idea for evdevremapkeys was to just stick a configureable folder first in sys.path and import every file in there, i just thought it was funny that we were doing somewhat similiar things.

Wanna drink beer and hack some day? 🥳

**Comment by codekuu** [comment]
I won't be able to help with the PR, too much on my plate right now!

My "program" is more for just handling inputs from devices. Mainly used as a gimmic during demos imo. Like automating configuration of network devices/ firewalls/ cloud with physical buttons. Or a big red panic button for lulz which blocks all incoming and outgoing packets 🤣

Hit me up on discord "codekuu"!
